-- ============================================================================
-- VMX Schema — converted from SQL Server to SQLite
-- Type mapping used:
--   varchar(n)          -> TEXT
--   numeric/decimal(p,0)-> INTEGER   (zero decimal places = whole number)
--   numeric/decimal(p,s)-> REAL      (s > 0, has fractional part)
--   float                -> REAL
--   date / datetime      -> TEXT     (store as ISO-8601, e.g. '2026-09-16' / '2026-09-16 14:30:00')
-- Dropped: [dbo]. schema prefix, ON [PRIMARY] filegroup clause, GO batch separators
-- (none of these have SQLite equivalents / meaning)
-- ============================================================================



PRAGMA foreign_keys = ON;

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_WELL (
    WELL_ID                TEXT NOT NULL,
    UWI                    TEXT,
    WELL_NAME               TEXT,
    LEGAL_NAME              TEXT,
    BLOCK                   TEXT,
    FIELD                   TEXT,
    COUNTY                  TEXT,
    DISTRICT                TEXT,
    REGION                  TEXT,
    STATE                   TEXT,
    COUNTRY                 TEXT,
    OPERATOR                TEXT,
    OPERATOR_DIV             TEXT,
    LICENSE_NO               TEXT,
    LICENSE_DATE             TEXT,
    PURPOSE                  TEXT,
    STATUS                   TEXT,
    SPUD_DATE                TEXT,
    PA_DATE                  TEXT,
    TIME_ZONE                TEXT,
    LONGITUDE                REAL,
    LATITUDE                 REAL,
    X_COORDINATE             REAL,
    Y_COORDINATE             REAL,
    PERM_DATUM               TEXT,
    WELL_HEAD_ELEVATION      REAL,
    GROUND_ELEVATION         REAL,
    WATER_DEPTH              REAL,
    WMLS_URL                 TEXT,
    WMLP_URL                 TEXT,
    ALARM_HISTORY_TABLE      TEXT,
    CREATED_BY               TEXT,
    CREATED_DATE             TEXT,
    MODIFIED_BY              TEXT,
    MODIFIED_DATE            TEXT,
    RIG_NAME                 TEXT,
    WELL_LAST_CHECKED        TEXT,
    WELL_FLAGGED             INTEGER,
    DATA_SOURCE              TEXT,
    ALARM_PROFILE_ID         TEXT,
    DATE_FORMAT              TEXT,
    EDR_PROVIDER             TEXT,
    DRILLING_SUP             TEXT,
    DRILLING_ENG             TEXT,
    WITSML_ID                TEXT,
    CONN_CHECK_TIME          TEXT,
    TRIP_CHECK_TIME          TEXT,
    LAST_CHECK_TIME          TEXT,
    LAST_ACK_TIME            TEXT,
    HISTORICAL               INTEGER,
    SEC                      TEXT,
    TWP                      TEXT,
    RGE                      TEXT,
    LEGAL_DESC               TEXT,
    CONT_TYPE                TEXT,
    RIG_TYPE                 TEXT,
    PUMP1_MODEL              TEXT,
    PUMP1_STROKE             TEXT,
    PUMP1_LINER              TEXT,
    PUMP2_MODEL              TEXT,
    PUMP2_STROKE             TEXT,
    PUMP2_LINER              TEXT,
    PUMP3_MODEL              TEXT,
    PUMP3_STROKE             TEXT,
    PUMP3_LINER              TEXT,
    REP                      TEXT,
    TOOL_PUSHER               TEXT,
    TIGHT_HOLE_NO             TEXT,
    REENTRY_NO                TEXT,
    COMMENTS                 TEXT,
    CONTRACTOR                TEXT,
    OBJECTIVE                 TEXT,
    TD_DATE                   TEXT,
    TD_FORMATION               TEXT,
    PUMP1                     TEXT,
    PUMP2                     TEXT,
    PUMP3                     TEXT,
    RIG_COST                  REAL,
    DRLG_CONN_TIME             REAL,
    TRIP_CONN_TIME             REAL,
    BTS_TIME                   REAL,
    STS_TIME                   REAL,
    STB_TIME                   REAL,
    TRIP_IN_SPEED               REAL,
    TRIP_OUT_SPEED              REAL,
    PLANNED_DAYS                REAL,
    LAST_DATE_TIME               TEXT,
    LAST_DEPTH                   REAL,
    LAST_HDTH                    REAL,
    LAST_RIG_STATE                REAL,
    LAST_RIG_STATE_COLOR          REAL,
    LAST_ALARM_DATE               TEXT,
    LAST_ALARM_STATUS             REAL,
    DOWNLOAD_STATUS               INTEGER,
    PIPE_LENGTH                   INTEGER,
    STAND_LENGTH                  INTEGER,
    PLANNED_DEPTH                 INTEGER,
    DRLG_ENG_DEPT                  TEXT,
    DRLG_OP_DEPT                   TEXT,
    WELL_OP_TYPE                   TEXT,
    BI                              TEXT,
    WELL_LOCATION                   TEXT,
    ROP_BENCHMARK                   REAL,
    PIPE_MOVE_BENCHMARK             REAL,
    TRIP_STAND_BENCHMARK            REAL,
    DRLG_CONN_DEVIATION             REAL,
    DRLG_STS_DEVIATION              REAL,
    ROP_DEVIATION                   REAL,
    TRIP_CONN_DEVIATION             REAL,
    PIPE_MOVE_DEVIATION             REAL,
    TRIP_STAND_DEVIATION            REAL,
    TRIP_OH_CONN_TIME                REAL,
    TRIP_CH_CONN_TIME                REAL,
    TRIP_IN_OH_SPEED                 REAL,
    TRIP_IN_CH_SPEED                 REAL,
    TRIP_OUT_OH_SPEED                REAL,
    TRIP_OUT_CH_SPEED                REAL,
    TRIP_STND_OH                     REAL,
    TRIP_STND_CH                     REAL,
    TRIP_JNT_OH                      REAL,
    TRIP_JNT_CH                      REAL,
    TRIP_GRS_OH                      REAL,
    TRIP_GRS_CH                      REAL,
    INFO_TABLE                       TEXT,
    CASING_PIPE_LENGTH                REAL,
    SPUD_DATE_TIME                    TEXT,
    DQI                                REAL,
    FREQUENCY                          REAL,
    DQI_TABLENAME                      TEXT,
    DISABLE_AUTO_TAG                   INTEGER,
    PRIMARY KEY (WELL_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_WELLBORE (
    WELL_ID                TEXT NOT NULL,
    WELLBORE_ID             TEXT NOT NULL,
    WELLBORE_NAME           TEXT,
    WELLBORE_TYPE           TEXT,
    WELLBORE_NO             TEXT,
    GOVT_NO                 TEXT,
    SHAPE                   TEXT,
    STATUS                  TEXT,
    PURPOSE                 TEXT,
    KICKOFF_DATE            TEXT,
    DAY_TARGET              INTEGER,
    MD_CURRENT              REAL,
    TVD_CURRENT             REAL,
    MD_KICKOFF              REAL,
    TVD_KICKOFF             REAL,
    MD_PLANNED              REAL,
    TVD_PLANNED             REAL,
    MD_SS_PLANNED           REAL,
    TVD_SS_PLANNED          REAL,
    WMLS_URL                TEXT,
    WMLP_URL                TEXT,
    CREATED_BY              TEXT,
    CREATED_DATE            TEXT,
    MODIFIED_BY             TEXT,
    MODIFIED_DATE           TEXT,
    PRIMARY KEY (WELLBORE_ID, WELL_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_TIME_LOG (
    WELL_ID                    TEXT NOT NULL,
    WELLBORE_ID                 TEXT NOT NULL,
    LOG_ID                      TEXT NOT NULL,
    LOG_NAME                    TEXT,
    RUN_NO                      TEXT,
    SERVICE_COMPANY             TEXT,
    COMMENTS                    TEXT,
    DATA_TABLE_NAME              TEXT,
    DESCRIPTION                 TEXT,
    MAX_DATE                    TEXT,
    MAX_DEPTH                   REAL,
    MIN_DATE                    TEXT,
    MIN_DEPTH                   REAL,
    WMLS_URL                    TEXT,
    WMLP_URL                    TEXT,
    LAST_DATA_RECEIVED_ON       TEXT,
    CREATED_BY                  TEXT,
    CREATED_DATE                TEXT,
    MODIFIED_BY                 TEXT,
    MODIFIED_DATE               TEXT,
    EDR_PROVIDER                 TEXT,
    PRIMARY_LOG                  INTEGER,
    REMARKS_LOG                  INTEGER,
    LAST_WRITE_DATE               TEXT,
    PI_WELL_ID                    TEXT,
    PI_WELLBORE_ID                TEXT,
    PI_LOG_ID                     TEXT,
    LINK_TO_PARENT                 INTEGER,
    LINK_WELL_ID                   TEXT,
    LINK_WELLBORE_ID               TEXT,
    LINK_LOG_ID                    TEXT,
    DUPLICATE_ACTION                INTEGER,
    DONT_CALC_HDTH                  INTEGER,
    STARTING_HDTH                   REAL,
    DETECT_SPIKES                   INTEGER,
    TL_PERCENT                      REAL,
    TIME_PERIOD                     INTEGER,
    NR_BTM_DISTANCE                 REAL,
    CMP_WINDOW                      REAL,
    OPEN_SPIKE                      INTEGER,
    ACTION_TYPE                     INTEGER,
    LAST_CHECK_DATE                  TEXT,
    MAX_CLOSE_TIME                   INTEGER,
    CREA_REP_ON_FORMATION            INTEGER,
    SNAP_JOB_ID                      TEXT,
    FORMATION_TOP                    TEXT,
    DEPTH_THRESHOLD                  REAL,
    FREQUENCY                        REAL,
    LAST_SNAP_SENT                    TEXT,
    DONT_MOVE_AHEAD                   INTEGER,
    PRIMARY KEY (LOG_ID, WELLBORE_ID, WELL_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_TIME_LOG_COLUMNS (
    WELL_ID                TEXT NOT NULL,
    WELLBORE_ID             TEXT NOT NULL,
    LOG_ID                  TEXT NOT NULL,
    MNEMONIC                TEXT NOT NULL,
    CHANNEL_NAME             TEXT,
    DATA_TYPE                TEXT,
    UNIT                      TEXT,
    UNIT_ID                   TEXT,
    VUMAX_UNIT_ID              TEXT,
    VALUE_TYPE                 INTEGER,
    VALUE_QUERY                 TEXT,
    WITSML_MNEMONIC              TEXT,
    CREATED_BY                   TEXT,
    CREATED_DATE                 TEXT,
    MODIFIED_BY                  TEXT,
    MODIFIED_DATE                TEXT,
    COLUMN_ORDER                  INTEGER,
    WRITE_BACK                    INTEGER,
    OFFSET                         REAL,
    NO_INTERPOLATE                 INTEGER,
    PI_MNEMONIC                     TEXT,
    IS_STOR_PROC                    INTEGER,
    STOR_PROC_PARAM                  TEXT,
    CURVE_ID                          INTEGER,
    PARENT_MNEMONIC                   TEXT,
    ORIG_UNIT_ID                      TEXT,
    PRIMARY KEY (LOG_ID, MNEMONIC, WELLBORE_ID, WELL_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_DEPTH_LOG (
    WELL_ID                TEXT NOT NULL,
    WELLBORE_ID             TEXT NOT NULL,
    LOG_ID                  TEXT NOT NULL,
    LOG_NAME                TEXT,
    RUN_NO                  TEXT,
    SERVICE_COMPANY         TEXT,
    COMMENTS                TEXT,
    DATA_TABLE_NAME          TEXT,
    DESCRIPTION              TEXT,
    MAX_DEPTH                REAL,
    MIN_DEPTH                REAL,
    WMLS_URL                 TEXT,
    WMLP_URL                 TEXT,
    LAST_DATA_RECEIVED_ON     TEXT,
    CREATED_BY                TEXT,
    CREATED_DATE              TEXT,
    MODIFIED_BY                TEXT,
    MODIFIED_DATE              TEXT,
    M_DEPTH                     REAL,
    EDR_PROVIDER                 TEXT,
    LAST_WRITE_DEPTH              REAL,
    PI_WELL_ID                     TEXT,
    PI_WELLBORE_ID                 TEXT,
    PI_LOG_ID                      TEXT,
    LINK_TO_PARENT                  INTEGER,
    LINK_WELL_ID                    TEXT,
    LINK_WELLBORE_ID                TEXT,
    LINK_LOG_ID                     TEXT,
    DUPLICATE_ACTION                 INTEGER,
    PRIMARY_LOG                      INTEGER,
    PRIMARY KEY (LOG_ID, WELLBORE_ID, WELL_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_DEPTH_LOG_COLUMNS (
    WELL_ID                TEXT NOT NULL,
    WELLBORE_ID             TEXT NOT NULL,
    LOG_ID                  TEXT NOT NULL,
    MNEMONIC                 TEXT NOT NULL,
    CHANNEL_NAME              TEXT,
    DATA_TYPE                 TEXT,
    UNIT                       TEXT,
    UNIT_ID                    TEXT,
    VUMAX_UNIT_ID               TEXT,
    VALUE_TYPE                  INTEGER,
    VALUE_QUERY                  TEXT,
    WITSML_MNEMONIC               TEXT,
    CREATED_BY                    TEXT,
    CREATED_DATE                  TEXT,
    MODIFIED_BY                   TEXT,
    MODIFIED_DATE                 TEXT,
    COLUMN_ORDER                   INTEGER,
    WRITE_BACK                     INTEGER,
    PI_MNEMONIC                     TEXT,
    AXIS_DATA_COUNT                  INTEGER,
    PARENT_MNEMONIC                   TEXT,
    ORIG_UNIT_ID                      TEXT,
    PRIMARY KEY (LOG_ID, MNEMONIC, WELLBORE_ID, WELL_ID)
);

-- ----------------------------------------------------------------------------
-- No primary key defined in the original source for this table (it's a
-- single-row settings/config table) — kept without a PK, matching the source.
CREATE TABLE IF NOT EXISTS VMX_COMMON_RIGSTATE_SETUP (
    UNKNOWN_NAME              TEXT,
    UNKNOWN_NUMBER             INTEGER,
    UNKNOWN_COLOR               INTEGER,
    HOOKLOAD_CUTOFF              REAL,
    RPM_CUTOFF                    REAL,
    CIRC_CUTOFF                    REAL,
    SENSITIVITY                     REAL,
    PUMP_PRESSURE_CUTOFF             REAL,
    DEPTH_COMP_SENSITIVITY            REAL,
    DETECT_AUTO_SLIDE                  INTEGER,
    MIN_TORQUE                          REAL,
    MAX_TORQUE                           REAL,
    CALIBRATION_ROWS                      INTEGER,
    MIN_TORQUE_DIFF                        REAL,
    MIN_RPM                                 REAL,
    MAX_RPM                                  REAL,
    SELECTED_SET                              INTEGER,
    MIN_TORQUE2                                REAL,
    MAX_TORQUE2                                 REAL,
    CALIBRATION_ROWS2                            INTEGER,
    MIN_TORQUE_DIFF2                              REAL,
    MIN_RPM2                                       REAL,
    MAX_RPM2                                        REAL,
    MIN_TORQUE3                                      REAL,
    MAX_TORQUE3                                       REAL,
    CALIBRATION_ROWS3                                  INTEGER,
    MIN_TORQUE_DIFF3                                    REAL,
    MIN_RPM3                                             REAL,
    MAX_RPM3                                              REAL,
    CREATED_BY                                             TEXT,
    CREATED_DATE                                           TEXT,
    MODIFIED_BY                                            TEXT,
    MODIFIED_DATE                                          TEXT,
    DETECT_AIR_DRILLING                                     INTEGER,
    AIR_PRESSURE                                             REAL,
    TORQUE_CUTOFF                                             REAL,
    TORQUE_CYCLES                                              INTEGER,
    CALB_TIME                                                   INTEGER,
    PERCENT_WINDOW                                               INTEGER,
    DETECT_PIPE_MOVE                                              INTEGER,
    PIPE_MOVE_THRESHOLD                                            REAL
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_COMMON_RIGSTATE_ITEMS (
    RIG_STATE_NUMBER       INTEGER NOT NULL,
    RIG_STATE_NAME          TEXT NOT NULL,
    RIG_STATE_COLOR          INTEGER,
    CREATED_BY                TEXT,
    CREATED_DATE              TEXT,
    MODIFIED_BY                TEXT,
    MODIFIED_DATE              TEXT,
    PRIMARY KEY (RIG_STATE_NUMBER)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_AKPI_DRLG_CONNECTIONS (
    WELL_ID                TEXT NOT NULL,
    ENTRY_ID                 INTEGER NOT NULL,
    DEPTH                     REAL,
    BOTTOM_TO_SLIPS            INTEGER,
    SLIPS_TO_SLIPS              INTEGER,
    SLIPS_TO_BOTTOM              INTEGER,
    FROM_DATE                     TEXT,
    TO_DATE                        TEXT,
    TIME                            TEXT,
    USER_COMMENT                     TEXT,
    CREATED_BY                        TEXT,
    CREATED_DATE                      TEXT,
    MODIFIED_BY                       TEXT,
    MODIFIED_DATE                     TEXT,
    LOCAL_FROM_DATE                    TEXT,
    LOCAL_TO_DATE                      TEXT,
    PRIMARY KEY (WELL_ID, ENTRY_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_AKPI_DRLG_STAND (
    WELL_ID                TEXT NOT NULL,
    ENTRY_ID                 INTEGER NOT NULL,
    DEPTH                     REAL,
    ROP                        REAL,
    ROTARY_ROP                  REAL,
    SLIDE_ROP                    REAL,
    FROM_DATE                     TEXT,
    TO_DATE                        TEXT,
    TIME                            TEXT,
    USER_COMMENT                     TEXT,
    CREATED_BY                        TEXT,
    CREATED_DATE                      TEXT,
    MODIFIED_BY                       TEXT,
    MODIFIED_DATE                     TEXT,
    LOCAL_FROM_DATE                    TEXT,
    LOCAL_TO_DATE                      TEXT,
    PRIMARY KEY (WELL_ID, ENTRY_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_AKPI_TRIP_CONNECTIONS (
    WELL_ID                TEXT NOT NULL,
    ENTRY_ID                 INTEGER NOT NULL,
    DEPTH                     REAL,
    SLIPS_TO_SLIPS             INTEGER,
    FROM_DATE                    TEXT,
    TO_DATE                       TEXT,
    TIME                           TEXT,
    USER_COMMENT                    TEXT,
    CREATED_BY                       TEXT,
    CREATED_DATE                     TEXT,
    MODIFIED_BY                      TEXT,
    MODIFIED_DATE                    TEXT,
    PIPE_MOVE_TIME                    REAL,
    LOCAL_FROM_DATE                    TEXT,
    LOCAL_TO_DATE                       TEXT,
    PRIMARY KEY (WELL_ID, ENTRY_ID)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_CONN_INFO (
    WELL_ID                TEXT NOT NULL,
    DEPTH                    REAL NOT NULL,
    CREATED_BY                TEXT,
    CREATED_DATE              TEXT,
    MODIFIED_BY                TEXT,
    MODIFIED_DATE              TEXT,
    PRIMARY KEY (WELL_ID, DEPTH)
);

-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS VMX_CON_ANNOTATIONS (
    WELL_ID                TEXT NOT NULL,
    DEPTH                    REAL NOT NULL,
    COMMENT                   TEXT,
    CREATED_BY                 TEXT,
    CREATED_DATE               TEXT,
    MODIFIED_BY                 TEXT,
    MODIFIED_DATE               TEXT,
    PRIMARY KEY (WELL_ID, DEPTH)
);
